### ISSUE TITLE
stm32 ic chip

### ISSUE THREAD

**Issue by rifatdanur** [WeActStudio/BluePill-Plus#16]
Does the stm32 bluepill weact studio use the original chip from st microelectronic?

**Comment by ZYQ-FEIYUE** [comment]
YES.You need to go to the official store to buy it.

**Comment by ZYQ-FEIYUE** [comment]
YES.You need to go to the official store to buy it.

**Comment by rifatdanur** [comment]
okay thanks, now I have found a board that has guaranteed quality and also uses the original ic
